name: subtree-matrix
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-downstream:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        path: [app1, app2, app3]

    name: Update downstream ${{ matrix.path }} package

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-trpc-main-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-trpc-main-

      - name: Install deps (with cache)
        run: pnpm install

      - name: Set `shared-workspace-lockfile` to false
        run: |
          echo "shared-workspace-lockfile=false" >> .npmrc

      - name: Install dependencies
        run: |
          pnpm install

      - name: Sync downstream
        uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: "juliusmarminge/git-subtree-test-${{ matrix.path }}"
          path: "apps/${{ matrix.path }}"
          deploy_key: ${{ secrets.SUBTREE_DEPLOY_KEY }}
          force: true # will force push to the downstream repository
